version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: ${DB_DATABASE}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: recommendation_trip_redis
    restart: unless-stopped
    ports:
      - '${QUEUE_REDIS_PORT}:6379'
    command: >
      sh -c "if [ -n \"$QUEUE_REDIS_PASSWORD\" ];
      then redis-server --requirepass \"$QUEUE_REDIS_PASSWORD\";
      else redis-server; fi"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local