export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const NOTIFICATION_PREFERENCE_REPOSITORY = Symbol(
  'NOTIFICATION_PREFERENCE_REPOSITORY',
);
export const NOTIFICATION_DELIVERY_REPOSITORY = Symbol(
  'NOTIFICATION_DELIVERY_REPOSITORY',
);
export const NOTIFICATION_DISPATCH = Symbol('NOTIFICATION_DISPATCH');
export const NOTIFICATION_EMAIL = Symbol('NOTIFICATION_EMAIL');
export const NOTIFICATION_QUEUE = Symbol('NOTIFICATION_QUEUE');
export const NOTIFICATION_USER_LOOKUP = Symbol('NOTIFICATION_USER_LOOKUP');
