export const CONVERSATION_REPOSITORY = Symbol('CONVERSATION_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const USER_LOOKUP = Symbol('USER_LOOKUP');
export const CHAT_REALTIME = Symbol('CHAT_REALTIME');
export const CHAT_SERVER_REGISTRY = Symbol('CHAT_SERVER_REGISTRY');
